language: node_js
node_js: 6
 
before_script:
 - "npm install"
# before_install:
#  - "apt-get install php7.0"
#  - "printf "\n" | pecl install pecl_http"
script:
  - "mocha test/unit/initial.test.js"
