matrix:
 include:
  - language: php
    php: '5.6'
    script: 
    - phpunit --help
  - language: node_js
    node_js:
      - "6"
    before_script:
      - "npm install"
    script:
      - "mocha test/unit/initial.test.js" 