matrix:
 include:
  language: python
  - python: "2.7"
    env: TEST_SUITE=suite_2_7
  - python: "3.3"
    env: TEST_SUITE=suite_3_3
  - python: "pypy"
    env: TEST_SUITE=suite_pypy
  script: ./test.py $TEST_SUITE

  - language: node_js
    node_js:
      - "6"
    before_script:
      - "npm install"
    script:
      - "mocha test/unit/initial.test.js" 
# language: python
# matrix:
#   include:
#   - python: "2.7"
#     env: TEST_SUITE=suite_2_7
#   - python: "3.3"
#     env: TEST_SUITE=suite_3_3
#   - python: "pypy"
#     env: TEST_SUITE=suite_pypy
# script: ./test.py $TEST_SUITE