matrix:
 include:
   language: php

    php:
      - 5.6
      - 7.0
      - 7.1
      - 7.2
      - nightly

    matrix:
      fast_finish: true
      allow_failures:
        - php: nightly

    install:
      - composer install --prefer-dist

    script:
      - vendor/bin/phpunit -d error_reporting=24575 --coverage-clover=coverage.xml

    after_success:
      - bash <(curl -s https://codecov.io/bash)

   - language: node_js
     node_js:
       - "6"
     before_script:
       - "npm install"
     script:
       - "mocha test/unit/initial.test.js"