language: php
php:
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
  
# image: node:6.9.4

# pipelines:
#   default:
#     - step:
#         caches:
#           - node
#         script:
#           - npm install
#           - npm run test-unit