matrix:
 include:
   - language: php
     php:
       - '5.6'
       - '7.1'
       - hhvm # on Trusty only
       - nightly

   - language: node_js
     node_js:
       - "6"
     before_script:
       - "npm install"
     script:
       - "node index.js"