language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
# matrix:
#  include:
#   - language: php
#     php: 5.6
#     dist: trusty
#     sudo: required

#   # - language: node_js
#   #   node_js:
#   #     - "6"
#   #   before_script:
#   #     - "npm install"
#   #   script:
#   #     - "mocha test/unit/initial.test.js" 